# Generated by Django 3.2.5 on 2021-07-10 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrator', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('enroll_no', models.PositiveIntegerField(unique=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.institute')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'faculties',
            },
        ),
    ]
