# Generated by Django 3.2.5 on 2021-07-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='email',
            field=models.EmailField(default='example@email.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='enroll_no',
            field=models.PositiveIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
