# Generated by Django 3.2.5 on 2021-07-15 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20210715_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='question',
            name='start_time',
        ),
    ]
