# Generated by Django 3.2.5 on 2021-07-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_auto_20210715_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='room_id',
            field=models.CharField(blank=True, default='room-<built-in function id>', max_length=10),
        ),
    ]
