# Generated by Django 3.2.5 on 2021-07-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_alter_course_room_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='total_marks',
        ),
        migrations.AlterField(
            model_name='course',
            name='room_id',
            field=models.CharField(blank=True, default='room-MQQRo', max_length=10),
        ),
    ]
