# Generated by Django 3.2.5 on 2021-07-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0009_auto_20210716_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='room_id',
            field=models.CharField(blank=True, default='room-vpigF', max_length=10),
        ),
    ]
