# Generated by Django 3.2.5 on 2021-07-16 18:55

from django.db import migrations, models
import utils.random_password


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0012_auto_20210716_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='room_id',
            field=models.CharField(blank=True, default=utils.random_password.generate_random_password, max_length=10),
        ),
    ]
