# Generated by Django 3.2.5 on 2021-07-04 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name of institute', max_length=200)),
                ('code', models.IntegerField(blank=True, help_text='Enter institute code', null=True)),
                ('city', models.CharField(help_text='Enter city', max_length=200)),
                ('state', models.CharField(help_text='Enter state', max_length=200)),
                ('country', models.CharField(help_text='Enter country', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administrator.institute')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
