# Generated by Django 3.2.5 on 2021-07-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_administrator_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='city',
            field=models.CharField(blank=True, help_text='Enter city', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='country',
            field=models.CharField(blank=True, help_text='Enter country', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='state',
            field=models.CharField(blank=True, help_text='Enter state', max_length=200, null=True),
        ),
    ]
