# Generated by Django 3.2.5 on 2021-07-04 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_auto_20210704_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='website_url',
            field=models.URLField(blank=True, help_text='Enter website url', null=True, validators=[django.core.validators.RegexValidator(message='Not a valid URL', regex='/^(https?:\\/\\/)?([\\da-z\\.-]+)\\.([a-z\\.]{2,6})([\\/\\w \\.-]*)*\\/?$/')]),
        ),
    ]
