# Generated by Django 3.2.5 on 2021-07-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_institute_website_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='website_url',
            field=models.URLField(blank=True, help_text='Enter website url', null=True),
        ),
    ]
