# Generated by Django 3.2.5 on 2021-07-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(blank=True, help_text='Enter subject name', max_length=200, null=True),
        ),
    ]
