# Generated by Django 3.2.5 on 2021-07-08 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
        ('faculty', '0002_auto_20210708_1911'),
        ('subject', '0002_alter_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.institute'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='faculty.faculty'),
        ),
    ]
