# Generated by Django 3.2.5 on 2021-07-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_assignmentinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assigned_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
