# Generated by Django 3.2.5 on 2021-07-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_auto_20210711_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentinstance',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
